version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
      - pip install taskcat

  build:
    commands:
      - echo "Running cfn-lint..."
      - cfn-lint --non-zero-exit-code error network/*.yaml
      - cfn-lint --non-zero-exit-code error security/*.yaml
      - cfn-lint --non-zero-exit-code error compute/*.yaml

artifacts:
  files:
    - '**/*'