AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  VpcId:
    Type: String

Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name
          Value: NT548-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId

Outputs:

  InternetGatewayId:
    Value: !Ref InternetGateway